In [2]:
import numpy as np
a=np.random.rand(10)
print(a)

[0.29072514 0.39258794 0.45028436 0.30977197 0.33338688 0.5152968
 0.56462324 0.31507882 0.11060192 0.14375747]


In [3]:
d = (a<0.5) & (a>0.3)
d

array([False,  True,  True,  True,  True, False, False,  True, False,
       False])

In [5]:
b=a[d]
b

array([0.39258794, 0.45028436, 0.30977197, 0.33338688, 0.31507882])

In [18]:
#d.indexof()
# tuple because could be 2d
np.where(d==True)

(array([1, 5, 8]),)

In [20]:
np.where(d>0)

(array([1, 5, 8]),)

In [21]:
d.sum()

3

In [25]:
e=~(d)
# inverse d
e.sum()

7

In [6]:
c=a<0.5
c

array([ True,  True,  True,  True, False,  True, False, False,  True,
       False])

In [7]:
c.all()

False

In [8]:
c.any()

True